* counsel-bbdb (v0.0.4)
Quick search&input email from [[https://www.emacswiki.org/emacs/CategoryBbdb][BBDB]] database based on Emacs API =completing-read=.

* Install
Place =counsel-bbdb.el= on your =load-path=, and add below setup:
#+begin_src elisp
(require 'counsel-bbdb)
#+end_src

Or just install it through [[http://melpa.org][melpa]].

* Usage
=M-x counsel-bbdb-complete-mail= to input email address.

=M-x counsel-bbdb-reload= to reload contacts from BBDB database.

=M-x counsel-bbdb-expand-mail-alias= to expand mail alias.

Mail alias is also called "Contact Group" or "Address Book Group" in other email clients.
* Tips
** Insert multiple mail address
For example, after =C-u M-x counsel-bbdb-complete-mail=, you can press =C-M-n= to input multiple mail address.
** Customize the inserted mail address
You can set =counsel-bbdb-customized-insert= to insert mail in your own way,
#+begin_src elisp
(setq counsel-bbdb-customized-insert
      (lambda (r append-comma)
        (let* ((family-name (nth 1 r))
               (given-name (nth 2 r))
               (display-name (nth 3 r))
               (mail (nth 4 r))))
        (insert (format "%s:%s:%s:%s%s"
                        given-name
                        family-name
                        display-name
                        mail
                        (if append-comma ", " " ")))))

#+end_src

* Bug Report
Check [[https://github.com/redguardtoo/counsel-bbdb]].

Please provides details of OS, Emacs, and Ivy.