* counsel-bbdb (v0.0.1)
Quick search&input email from [[https://www.emacswiki.org/emacs/CategoryBbdb][BBDB]] database based on [[https://github.com/abo-abo/swiper][ivy-mode]]

Features:
- Quick
- Smart, know some ethic groups display family name before given name
- Robust, only dependency is [[https://github.com/abo-abo/swiper][ivy-mode]]. NO API from =bbdb= is used

* Install
Place counsel-bbdb.el on your =load-path=, and add this to your configuration:
#+begin_src elisp
(require 'counsel-bbdb)
#+end_src

Or just install it through [[http://melpa.org][melpa]].

Ivy 8, Emacs 24.3 is required.
* Usage
=M-x counsel-bbdb-complete-mail= to input email address.

=M-x counsel-bbdb-reload= to reload contacts from BBDB database.

* Tips
** Insert multiple mail address
Since =counsel-bbdb= is based ivy-mode. All ivy key bindings are supported.

For example, after =C-u M-x counsel-bbdb-complete-mail=, you can press =C-M-n= to input multiple mail address.
** Customize the inserted mail address
You can set =counsel-bbdb-customized-insert= to insert mail in your own way,
#+begin_src elisp
(setq counsel-bbdb-customized-insert
      (lambda (r append-comma)
        (let* ((family-name (nth 1 r))
               (given-name (nth 2 r))
               (display-name (nth 3 r))
               (mail (nth 4 r))))
        (insert (format "%s:%s:%s:%s%s"
                        given-name
                        family-name
                        display-name
                        mail
                        (if append-comma ", " " ")))))

#+end_src

BTW, =ivy-resume= is fully supported.
* Bug Report
Check [[https://github.com/redguardtoo/counsel-bbdb]].

Please provides details of OS, Emacs, and Ivy.